service: infrastructure
provider:
  name: aws
  stage: ${opt:stage, dev} # Set the default stage used. Default is dev
  region: ${opt:region, af-south-1} # Overwrite the default region used. Default is us-east-1
  stackName: ${opt:stage}-${self:service}-stack # Use a custom name for the CloudFormation stack

resources:
  - Conditions:
      Az1:
        Fn::Equals:
          - ${file(cicd/env/${opt:region}/${opt:stage}.yml):Az1}
          - true
      Az2:
        Fn::Equals:
          - ${file(cicd/env/${opt:region}/${opt:stage}.yml):Az2}
          - true
      Az3:
        Fn::Equals:
          - ${file(cicd/env/${opt:region}/${opt:stage}.yml):Az3}
          - true
      MySql:
        Fn::Equals:
          - ${file(cicd/env/${opt:region}/${opt:stage}.yml):MySql}
          - true
      MsSql:
        Fn::Equals:
          - ${file(cicd/env/${opt:region}/${opt:stage}.yml):MsSql}
          - true
      GlobalConnect:
        Fn::Equals:
          - true # If you toggle this to false, not transit network will be deployed
          - true
  - Resources:
  - ${file(cicd/resources/networking/vpc.serverless.yml)}
  - ${file(cicd/resources/networking/subnet.serverless.yml)}
  - ${file(cicd/resources/networking/gateways.serverless.yml)}
  - ${file(cicd/resources/networking/routes.serverless.yml)}
  - ${file(cicd/resources/networking/sg.serverless.yml)}
  - ${file(cicd/resources/networking/transitgw.serverless.yml)}
 